spring.application.name=Actuator-demo
server.port=1001

#enabled actuator endpoints

management.endpoints.web.exposure.include=health,info,metrics
management.info.env.enabled=true
info.app.name=Actuator Demo App
info.app.version=1.0
info.app.description=actuator example for fresher


